### PR TITLE
set `options: {strict: true}` to cause unimplemented steps to be reported as a failure

### PR DESCRIPTION
**Pull request by nalbion**
as proposed in #25

### CODE REVIEW

**Comment by nalbion** [comment]
... the call in the `bin` directory should parse options from the command line. 

The README should be updated to document the command line options and provide an example for invoking from Gulp

**Comment by stjohnjohnson** [comment]
This is great!  Still need to add support for calling it from the bin and updating the README.  Are you planning on doing that or would like me to step in?

**Comment by nalbion** [comment]
Yeah, I could add yargs as a dependency and support

```
--strict --indent 4 --encoding "UTF-8"
```

With short aliases `-s -i 4 -e "UTF-8"` and help

**Comment by nalbion** [comment]
@stjohnjohnson - done

**Comment by stjohnjohnson** [comment]
Amazing!  Thanks for the great contribution!!
cucumber cats

**Comment by stjohnjohnson** [comment]
+ cucumber-junit@1.6.0

**Pull request merged**
